#!/bin/awk
#
# this script calculate nr. of migration of task given in input
# according to trace file generated by sched_switch tracer


BEGIN {

	# 0: running
	# 1: sleeping
	taskstate = 1
	len = 0;
	str = 0;

	last_cpu = -1
	nr_migration = 0;

	n = 0;
	print "#list of exec. time"
}

$0 !~ /==>/ {
	next
}

$NF == task {

	#task is entering
	if(taskstate == 0) {
		#print "ERROR: " task " was already running..."
		next
	}
	
	#store last cpu that executed me
	new_cpu = $(NF-2);
	if(new_cpu != last_cpu && last_cpu != -1)
		nr_migration++;
	
	last_cpu=new_cpu;

	#printf("##%s entering.. ",task)
	taskstate = 0
	len=match($3,":");
	timestamp1=substr($3,0,len-1);
	#printf ("##%.06f\n", timestamp1)
}

$1 ~ task {
	#task is leaving
	if(taskstate == 1) {
	#	print "ERROR: " task " already sleeping..."
		next
	}
	taskstate=1
	len=match($3,":");
	timestamp2=substr($3,0,len-1);

	exec_time=timestamp2-timestamp1
	exec_time*=1000000
	print exec_time " " timestamp2
	n++
}


END{
	print "#nr_migr: " nr_migration
}
